"""VSA-Driven Language Generator.

Replaces template-based Responder with concept-composed generation.

Architecture:
  VSA Concepts → Concept Chains → Phrase Assembly → Sentence Composition

Key idea: Natural language is generated by traversing activated concepts
in the VSA space and mapping them to words/phrases, then composing into
syntactically valid sentences using scaffolding patterns.

Supports:
  - Physics reasoning responses
  - Code generation (pattern-based)
  - Abstract concept explanations
  - Dynamic vocabulary expansion
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from ..vsa_store import AttributePrimitivePool, RecipeStore, ConceptSynthesizer


# ---------------------------------------------------------------------------
# Word and Phrase representations
# ---------------------------------------------------------------------------

@dataclass
class WordEntry:
    """A word in the generator's vocabulary."""
    text: str
    pos: str  # part of speech: noun, verb, adj, adv, prep, det, conj
    category: str = ""  # VSA category (shape, color, material, ...)
    tags: List[str] = field(default_factory=list)  # semantic tags


@dataclass
class PhraseTemplate:
    """A phrase template with slots to fill."""
    pattern: str  # e.g., "{adj} {noun}", "the {noun} {verb}"
    pos_sequence: str  # e.g., "ADJ NOUN", "DET NOUN VERB"
    description: str = ""


@dataclass
class CodePattern:
    """A code generation pattern."""
    name: str
    language: str  # python, javascript, c, etc.
    description: str
    template: str  # code template with {slots}
    keywords: List[str] = field(default_factory=list)
    input_types: List[str] = field(default_factory=list)
    output_type: str = ""


# ---------------------------------------------------------------------------
# Concept-to-Language Mapper
# ---------------------------------------------------------------------------

class ConceptWordMapper:
    """Maps VSA concepts back to natural language.

    This is the inverse of TextToVSA: given a concept (attribute ID or VSA
    vector), find the best natural language expression.
    """

    def __init__(self, primitives: AttributePrimitivePool):
        self.primitives = primitives

        # {attr_id: WordEntry} -- maps VSA attribute IDs to words
        self._word_map: Dict[str, WordEntry] = {}

        # {word_text: WordEntry} -- reverse lookup
        self._text_map: Dict[str, WordEntry] = {}

        # Phrase templates for different concept combinations
        self._phrase_templates: List[PhraseTemplate] = []

        self._init_default_mappings()

    def _init_default_mappings(self):
        """Initialize default concept-to-word mappings."""
        # Shape → noun
        shape_words = {
            "sphere": WordEntry("sphere", "noun", "shape", ["object"]),
            "cube": WordEntry("cube", "noun", "shape", ["object"]),
            "cylinder": WordEntry("cylinder", "noun", "shape", ["object"]),
            "capsule": WordEntry("capsule", "noun", "shape", ["object"]),
            "cone": WordEntry("cone", "noun", "shape", ["object"]),
            "flat": WordEntry("flat surface", "noun", "shape", ["object"]),
        }
        # Color → adjective
        color_words = {
            "red": WordEntry("red", "adj", "color", ["visual"]),
            "green": WordEntry("green", "adj", "color", ["visual"]),
            "blue": WordEntry("blue", "adj", "color", ["visual"]),
            "yellow": WordEntry("yellow", "adj", "color", ["visual"]),
            "white": WordEntry("white", "adj", "color", ["visual"]),
            "black": WordEntry("black", "adj", "color", ["visual"]),
            "orange": WordEntry("orange", "adj", "color", ["visual"]),
            "purple": WordEntry("purple", "adj", "color", ["visual"]),
        }
        # Material → adjective/noun
        material_words = {
            "metal": WordEntry("metal", "adj", "material", ["tactile"]),
            "wood": WordEntry("wooden", "adj", "material", ["tactile"]),
            "plastic": WordEntry("plastic", "adj", "material", ["tactile"]),
            "rubber": WordEntry("rubber", "adj", "material", ["tactile"]),
            "glass": WordEntry("glass", "adj", "material", ["tactile"]),
            "stone": WordEntry("stone", "adj", "material", ["tactile"]),
            "fabric": WordEntry("fabric", "adj", "material", ["tactile"]),
        }
        # Mass → adjective
        mass_words = {
            "very_light": WordEntry("very light", "adj", "mass", ["physical"]),
            "light": WordEntry("light", "adj", "mass", ["physical"]),
            "medium": WordEntry("medium-weight", "adj", "mass", ["physical"]),
            "heavy": WordEntry("heavy", "adj", "mass", ["physical"]),
            "very_heavy": WordEntry("very heavy", "adj", "mass", ["physical"]),
        }
        # Elasticity → adjective
        elasticity_words = {
            "rigid": WordEntry("rigid", "adj", "elasticity", ["physical"]),
            "stiff": WordEntry("stiff", "adj", "elasticity", ["physical"]),
            "elastic": WordEntry("elastic", "adj", "elasticity", ["physical"]),
            "soft": WordEntry("soft", "adj", "elasticity", ["physical"]),
            "fluid": WordEntry("fluid", "adj", "elasticity", ["physical"]),
        }
        # Texture → adjective
        texture_words = {
            "smooth": WordEntry("smooth", "adj", "texture", ["tactile"]),
            "rough": WordEntry("rough", "adj", "texture", ["tactile"]),
            "sticky": WordEntry("sticky", "adj", "texture", ["tactile"]),
            "slippery": WordEntry("slippery", "adj", "texture", ["tactile"]),
        }
        # Temperature → adjective
        temperature_words = {
            "cold": WordEntry("cold", "adj", "temperature", ["thermal"]),
            "cool": WordEntry("cool", "adj", "temperature", ["thermal"]),
            "warm": WordEntry("warm", "adj", "temperature", ["thermal"]),
            "hot": WordEntry("hot", "adj", "temperature", ["thermal"]),
        }

        # Register all mappings
        all_maps = [
            shape_words, color_words, material_words, mass_words,
            elasticity_words, texture_words, temperature_words,
        ]
        for word_map in all_maps:
            for name, entry in word_map.items():
                attr_id = f"{entry.category}_{name}"
                self._word_map[attr_id] = entry
                self._text_map[entry.text] = entry

    def register_word(self, attr_id: str, word: str, pos: str,
                      category: str = "", tags: Optional[List[str]] = None):
        """Register a new concept-to-word mapping."""
        entry = WordEntry(word, pos, category, tags or [])
        self._word_map[attr_id] = entry
        self._text_map[word] = entry

    def attr_to_word(self, attr_id: str) -> Optional[WordEntry]:
        """Map an attribute ID to its word entry."""
        return self._word_map.get(attr_id)

    def concept_to_word(self, category: str, name: str) -> Optional[WordEntry]:
        """Map a (category, name) pair to its word entry."""
        attr_id = f"{category}_{name}"
        return self._word_map.get(attr_id)

    def describe_attributes(self, attr_ids: List[str]) -> List[WordEntry]:
        """Convert a list of attribute IDs to word entries."""
        entries = []
        for attr_id in attr_ids:
            entry = self._word_map.get(attr_id)
            if entry is not None:
                entries.append(entry)
        return entries

    def find_word(self, text: str) -> Optional[WordEntry]:
        """Find a word entry by its text."""
        return self._text_map.get(text)


# ---------------------------------------------------------------------------
# Sentence Scaffolding
# ---------------------------------------------------------------------------

class SentenceScaffolder:
    """Provides syntactic scaffolding for sentence generation.

    Given a semantic intent and available concepts, selects appropriate
    sentence patterns and fills them.
    """

    def __init__(self, mapper: ConceptWordMapper):
        self.mapper = mapper

        # Sentence patterns by intent
        self._patterns: Dict[str, List[str]] = {
            "prediction": [
                "The {adj} {noun} will {verb} because of {cause}.",
                "When released, the {adj} {noun} {verb_phrase}.",
                "Due to {cause}, the {noun} {verb_phrase}.",
            ],
            "explanation": [
                "{concept} is {definition}.",
                "{concept} refers to {definition}.",
                "In physics, {concept} means {definition}.",
            ],
            "description": [
                "The {adj1} {adj2} {noun} is {property}.",
                "This is a {adj} {noun} made of {material}.",
                "I see a {adj} {noun} with {property}.",
            ],
            "counterfactual": [
                "If {condition}, then {prediction}.",
                "In a scenario where {condition}, {prediction}.",
                "Suppose {condition}. Then {prediction}.",
            ],
            "action": [
                "I will {verb} the {noun}.",
                "To {goal}, I need to {verb} the {noun}.",
                "Plan: {steps}.",
            ],
            "code": [
                "Here's a {language} function that {description}:\n\n```{language}\n{code}\n```",
                "I can write that in {language}:\n\n```{language}\n{code}\n```",
            ],
            "abstract": [
                "{concept} implies {implication}.",
                "From {concept}, we can derive {implication}.",
                "The principle of {concept} leads to {implication}.",
            ],
        }

    def get_pattern(self, intent: str) -> str:
        """Get a sentence pattern for an intent."""
        patterns = self._patterns.get(intent, ["{text}"])
        return patterns[0]  # Simple selection; could be smarter

    def fill_pattern(self, pattern: str, slots: Dict[str, str]) -> str:
        """Fill a pattern with slot values."""
        result = pattern
        for key, value in slots.items():
            result = result.replace(f"{{{key}}}", str(value))
        # Clean up unfilled slots
        result = re.sub(r'\{[a-z_]+\}', '', result)
        result = re.sub(r'\s+', ' ', result).strip()
        return result


# ---------------------------------------------------------------------------
# VSA Language Generator
# ---------------------------------------------------------------------------

class VSALanguageGenerator:
    """Generate natural language from VSA concepts.

    This is the core generator that replaces template-based Responder.
    It composes text by:
      1. Activating concept chains from reasoning results
      2. Mapping concepts to words/phrases
      3. Assembling into sentences using scaffolding
    """

    def __init__(self, primitives: AttributePrimitivePool,
                 recipe_store: RecipeStore):
        self.primitives = primitives
        self.recipe_store = recipe_store
        self.synthesizer = ConceptSynthesizer(recipe_store)
        self.mapper = ConceptWordMapper(primitives)
        self.scaffolder = SentenceScaffolder(self.mapper)

        # Code pattern library
        self._code_patterns: Dict[str, CodePattern] = {}
        self._init_code_patterns()

        # Knowledge definitions for physics concepts
        self._definitions = self._init_definitions()

    def _init_definitions(self) -> Dict[str, dict]:
        """Initialize physics concept definitions."""
        return {
            "gravity": {
                "definition": "the force that attracts objects toward each other",
                "physics": "Objects accelerate downward at 9.8 m/s^2 near Earth's surface",
                "examples": ["dropping a ball", "an apple falling from a tree"],
            },
            "elasticity": {
                "definition": "the ability of a material to return to its original shape after deformation",
                "physics": "Elastic materials store and release potential energy",
                "examples": ["rubber band stretching", "ball bouncing off the floor"],
            },
            "friction": {
                "definition": "the force that opposes relative motion between surfaces",
                "physics": "Friction force is proportional to the normal force",
                "examples": ["brakes stopping a car", "sandpaper smoothing wood"],
            },
            "momentum": {
                "definition": "the product of mass and velocity (p = mv)",
                "physics": "Momentum is conserved in all collisions",
                "examples": ["a bowling ball hitting pins", "billiard balls colliding"],
            },
            "inertia": {
                "definition": "the tendency of an object to resist changes in its state of motion",
                "physics": "Newton's First Law: an object at rest stays at rest, in motion stays in motion",
                "examples": ["feeling pushed back when a car accelerates"],
            },
            "energy": {
                "definition": "the capacity to do work or cause change",
                "physics": "Energy is conserved; it transforms between kinetic and potential forms",
                "examples": ["a roller coaster converting height to speed"],
            },
            "force": {
                "definition": "an interaction that changes the motion of an object",
                "physics": "F = ma; force equals mass times acceleration",
                "examples": ["pushing a door open", "kicking a ball"],
            },
        }

    def _init_code_patterns(self):
        """Initialize the code pattern library."""
        patterns = [
            CodePattern(
                name="function_def",
                language="python",
                description="define a function",
                template="def {name}({params}):\n    \"\"\"{docstring}\"\"\"\n    {body}\n    return {return_value}",
                keywords=["function", "define", "def", "函数", "定义"],
                input_types=["any"],
                output_type="any",
            ),
            CodePattern(
                name="class_def",
                language="python",
                description="define a class",
                template="class {name}:\n    \"\"\"{docstring}\"\"\"\n\n    def __init__(self{params}):\n        {init_body}\n\n    {methods}",
                keywords=["class", "define class", "类", "定义类"],
                input_types=[],
                output_type="class",
            ),
            CodePattern(
                name="for_loop",
                language="python",
                description="iterate over a sequence",
                template="for {item} in {iterable}:\n    {body}",
                keywords=["loop", "iterate", "for", "循环", "遍历"],
                input_types=["iterable"],
                output_type="any",
            ),
            CodePattern(
                name="list_comprehension",
                language="python",
                description="create a list with comprehension",
                template="[{expr} for {item} in {iterable}{condition}]",
                keywords=["comprehension", "list", "列表推导"],
                input_types=["iterable"],
                output_type="list",
            ),
            CodePattern(
                name="if_else",
                language="python",
                description="conditional branching",
                template="if {condition}:\n    {then_body}\nelse:\n    {else_body}",
                keywords=["if", "else", "condition", "条件", "如果"],
                input_types=["bool"],
                output_type="any",
            ),
            CodePattern(
                name="try_except",
                language="python",
                description="error handling",
                template="try:\n    {try_body}\nexcept {exception} as e:\n    {except_body}",
                keywords=["try", "except", "error", "handle", "错误处理", "异常"],
                input_types=[],
                output_type="any",
            ),
            CodePattern(
                name="sort_list",
                language="python",
                description="sort a list",
                template="def {name}(arr):\n    \"\"\"Sort a list using quicksort.\"\"\"\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    middle = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return {name}(left) + middle + {name}(right)",
                keywords=["sort", "order", "排序", "quicksort", "快速排序"],
                input_types=["list"],
                output_type="list",
            ),
            CodePattern(
                name="read_file",
                language="python",
                description="read a file",
                template="with open('{path}', 'r', encoding='utf-8') as f:\n    {var} = f.read()",
                keywords=["read", "file", "open", "读取", "文件"],
                input_types=["str"],
                output_type="str",
            ),
            CodePattern(
                name="write_file",
                language="python",
                description="write to a file",
                template="with open('{path}', 'w', encoding='utf-8') as f:\n    f.write({content})",
                keywords=["write", "file", "save", "写入", "文件", "保存"],
                input_types=["str"],
                output_type="None",
            ),
            CodePattern(
                name="http_request",
                language="python",
                description="make an HTTP request",
                template="import requests\nresponse = requests.{method}('{url}'{extra})\ndata = response.json()",
                keywords=["http", "request", "api", "fetch", "请求", "接口"],
                input_types=["str"],
                output_type="dict",
            ),
            CodePattern(
                name="data_pipeline",
                language="python",
                description="process data through a pipeline",
                template="def {name}_pipeline(data):\n    # Step 1: {step1_desc}\n    data = {step1}\n    # Step 2: {step2_desc}\n    data = {step2}\n    # Step 3: {step3_desc}\n    data = {step3}\n    return data",
                keywords=["pipeline", "process", "transform", "管道", "处理", "转换"],
                input_types=["any"],
                output_type="any",
            ),
            CodePattern(
                name="async_function",
                language="python",
                description="define an async function",
                template="async def {name}({params}):\n    {body}\n    return {return_value}",
                keywords=["async", "await", "asynchronous", "异步"],
                input_types=["any"],
                output_type="any",
            ),
            CodePattern(
                name="generator",
                language="python",
                description="define a generator function",
                template="def {name}({params}):\n    for {item} in {iterable}:\n        yield {expr}",
                keywords=["generator", "yield", "生成器"],
                input_types=["iterable"],
                output_type="generator",
            ),
            CodePattern(
                name="decorator",
                language="python",
                description="define a decorator",
                template="def {name}(func):\n    def wrapper(*args, **kwargs):\n        {pre_logic}\n        result = func(*args, **kwargs)\n        {post_logic}\n        return result\n    return wrapper",
                keywords=["decorator", "wrap", "装饰器"],
                input_types=["callable"],
                output_type="callable",
            ),
            CodePattern(
                name="binary_search",
                language="python",
                description="binary search on sorted list",
                template="def binary_search(arr, target):\n    lo, hi = 0, len(arr) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1",
                keywords=["binary", "search", "二分查找", "搜索", "查找"],
                input_types=["list"],
                output_type="int",
            ),
            CodePattern(
                name="linked_list",
                language="python",
                description="singly linked list implementation",
                template="class Node:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\nclass LinkedList:\n    def __init__(self):\n        self.head = None\n\n    def append(self, val):\n        if not self.head:\n            self.head = Node(val)\n        else:\n            cur = self.head\n            while cur.next:\n                cur = cur.next\n            cur.next = Node(val)",
                keywords=["linked list", "链表"],
                input_types=[],
                output_type="class",
            ),
            CodePattern(
                name="stack",
                language="python",
                description="stack implementation",
                template="class Stack:\n    def __init__(self):\n        self._items = []\n\n    def push(self, item):\n        self._items.append(item)\n\n    def pop(self):\n        return self._items.pop()\n\n    def peek(self):\n        return self._items[-1]\n\n    def is_empty(self):\n        return len(self._items) == 0",
                keywords=["stack", "栈"],
                input_types=[],
                output_type="class",
            ),
            CodePattern(
                name="queue",
                language="python",
                description="queue implementation",
                template="from collections import deque\n\nclass Queue:\n    def __init__(self):\n        self._items = deque()\n\n    def enqueue(self, item):\n        self._items.append(item)\n\n    def dequeue(self):\n        return self._items.popleft()\n\n    def is_empty(self):\n        return len(self._items) == 0",
                keywords=["queue", "队列"],
                input_types=[],
                output_type="class",
            ),
            CodePattern(
                name="graph_bfs",
                language="python",
                description="breadth-first search on graph",
                template="from collections import deque\n\ndef bfs(graph, start):\n    visited = set([start])\n    queue = deque([start])\n    order = []\n    while queue:\n        node = queue.popleft()\n        order.append(node)\n        for neighbor in graph[node]:\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)\n    return order",
                keywords=["bfs", "breadth first", "广度优先", "图"],
                input_types=["graph"],
                output_type="list",
            ),
            CodePattern(
                name="graph_dfs",
                language="python",
                description="depth-first search on graph",
                template="def dfs(graph, start, visited=None):\n    if visited is None:\n        visited = set()\n    visited.add(start)\n    order = [start]\n    for neighbor in graph[start]:\n        if neighbor not in visited:\n            order.extend(dfs(graph, neighbor, visited))\n    return order",
                keywords=["dfs", "depth first", "深度优先"],
                input_types=["graph"],
                output_type="list",
            ),
            CodePattern(
                name="dynamic_programming",
                language="python",
                description="dynamic programming template",
                template="def dp_{problem}(n):\n    memo = [0] * (n + 1)\n    memo[0] = {base_case_0}\n    memo[1] = {base_case_1}\n    for i in range(2, n + 1):\n        memo[i] = {recurrence}\n    return memo[n]",
                keywords=["dp", "dynamic programming", "动态规划"],
                input_types=["int"],
                output_type="int",
            ),
            # --- Extended algorithms ---
            CodePattern(
                name="merge_sort",
                language="python",
                description="merge sort algorithm",
                template="def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result",
                keywords=["merge sort", "merge", "归并排序", "归并"],
                input_types=["list"],
                output_type="list",
            ),
            CodePattern(
                name="heap_sort",
                language="python",
                description="heap sort algorithm",
                template="def heap_sort(arr):\n    n = len(arr)\n    # Build max heap\n    for i in range(n // 2 - 1, -1, -1):\n        heapify(arr, n, i)\n    # Extract elements\n    for i in range(n - 1, 0, -1):\n        arr[0], arr[i] = arr[i], arr[0]\n        heapify(arr, i, 0)\n    return arr\n\ndef heapify(arr, n, i):\n    largest = i\n    left = 2 * i + 1\n    right = 2 * i + 2\n    if left < n and arr[left] > arr[largest]:\n        largest = left\n    if right < n and arr[right] > arr[largest]:\n        largest = right\n    if largest != i:\n        arr[i], arr[largest] = arr[largest], arr[i]\n        heapify(arr, n, largest)",
                keywords=["heap sort", "heap", "堆排序", "堆"],
                input_types=["list"],
                output_type="list",
            ),
            CodePattern(
                name="dijkstra",
                language="python",
                description="Dijkstra shortest path algorithm",
                template="import heapq\n\ndef dijkstra(graph, start):\n    distances = {node: float('inf') for node in graph}\n    distances[start] = 0\n    pq = [(0, start)]\n    while pq:\n        curr_dist, curr_node = heapq.heappop(pq)\n        if curr_dist > distances[curr_node]:\n            continue\n        for neighbor, weight in graph[curr_node].items():\n            distance = curr_dist + weight\n            if distance < distances[neighbor]:\n                distances[neighbor] = distance\n                heapq.heappush(pq, (distance, neighbor))\n    return distances",
                keywords=["dijkstra", "shortest path", "最短路径", "迪杰斯特拉"],
                input_types=["graph"],
                output_type="dict",
            ),
            CodePattern(
                name="binary_tree",
                language="python",
                description="binary tree implementation",
                template="class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\nclass BinaryTree:\n    def __init__(self):\n        self.root = None\n\n    def insert(self, val):\n        if not self.root:\n            self.root = TreeNode(val)\n        else:\n            self._insert_recursive(self.root, val)\n\n    def _insert_recursive(self, node, val):\n        if val < node.val:\n            if node.left is None:\n                node.left = TreeNode(val)\n            else:\n                self._insert_recursive(node.left, val)\n        else:\n            if node.right is None:\n                node.right = TreeNode(val)\n            else:\n                self._insert_recursive(node.right, val)",
                keywords=["binary tree", "tree", "bst", "二叉树", "树"],
                input_types=[],
                output_type="class",
            ),
            CodePattern(
                name="hash_map",
                language="python",
                description="hash map implementation",
                template="class HashMap:\n    def __init__(self, size=1000):\n        self.size = size\n        self.buckets = [[] for _ in range(size)]\n\n    def _hash(self, key):\n        return hash(key) % self.size\n\n    def put(self, key, value):\n        idx = self._hash(key)\n        bucket = self.buckets[idx]\n        for i, (k, v) in enumerate(bucket):\n            if k == key:\n                bucket[i] = (key, value)\n                return\n        bucket.append((key, value))\n\n    def get(self, key):\n        idx = self._hash(key)\n        for k, v in self.buckets[idx]:\n            if k == key:\n                return v\n        raise KeyError(key)",
                keywords=["hash map", "hash table", "dictionary", "哈希", "字典"],
                input_types=[],
                output_type="class",
            ),
            CodePattern(
                name="lru_cache",
                language="python",
                description="LRU cache implementation",
                template="from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity: int):\n        self.cache = OrderedDict()\n        self.capacity = capacity\n\n    def get(self, key: int) -> int:\n        if key not in self.cache:\n            return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n\n    def put(self, key: int, value: int) -> None:\n        if key in self.cache:\n            self.cache.move_to_end(key)\n        self.cache[key] = value\n        if len(self.cache) > self.capacity:\n            self.cache.popitem(last=False)",
                keywords=["lru", "cache", "缓存"],
                input_types=[],
                output_type="class",
            ),
            CodePattern(
                name="api_endpoint",
                language="python",
                description="Flask API endpoint",
                template="from flask import Flask, jsonify, request\n\napp = Flask(__name__)\n\n@app.route('/{endpoint}', methods=['{method}'])\ndef {name}():\n    if request.method == 'GET':\n        {get_logic}\n        return jsonify({{'data': result}})\n    elif request.method == 'POST':\n        data = request.get_json()\n        {post_logic}\n        return jsonify({{'status': 'success'}}), 201",
                keywords=["api", "endpoint", "flask", "rest", "接口"],
                input_types=[],
                output_type="dict",
            ),
            CodePattern(
                name="database_query",
                language="python",
                description="SQL database query",
                template="import sqlite3\n\ndef {name}(db_path, {params}):\n    conn = sqlite3.connect(db_path)\n    cursor = conn.cursor()\n    try:\n        cursor.execute('{query}', ({query_params}))\n        result = cursor.fetchall()\n        return result\n    finally:\n        conn.close()",
                keywords=["database", "sql", "query", "数据库", "查询"],
                input_types=["str"],
                output_type="list",
            ),
            CodePattern(
                name="test_function",
                language="python",
                description="unit test function",
                template="import unittest\n\nclass Test{name}(unittest.TestCase):\n    def test_{case}(self):\n        # Arrange\n        {arrange}\n        # Act\n        result = {act}\n        # Assert\n        self.assertEqual(result, {expected})\n\nif __name__ == '__main__':\n    unittest.main()",
                keywords=["test", "unit test", "testing", "测试", "单元测试"],
                input_types=[],
                output_type="None",
            ),
        ]
        for p in patterns:
            self._code_patterns[p.name] = p

    # ------------------------------------------------------------------
    # Core generation methods
    # ------------------------------------------------------------------

    def generate_description(self, object_id: str) -> str:
        """Generate a natural language description of an object from its recipe."""
        recipe = self.recipe_store.get_recipe(object_id)
        if recipe is None:
            return f"I don't know about '{object_id}'."

        entries = self.mapper.describe_attributes(recipe)
        if not entries:
            return f"I recognize '{object_id}' but can't describe it yet."

        # Group by part of speech
        adjs = [e.text for e in entries if e.pos == "adj"]
        nouns = [e.text for e in entries if e.pos == "noun"]

        noun_phrase = nouns[0] if nouns else "object"
        if adjs:
            adj_str = ", ".join(adjs[:-1]) + " and " + adjs[-1] if len(adjs) > 1 else adjs[0]
            return f"a {adj_str} {noun_phrase}"
        return f"a {noun_phrase}"

    def generate_prediction(self, subject: str, prediction: str,
                            cause: str = "", details: Optional[List[str]] = None) -> str:
        """Generate a prediction response from VSA concepts."""
        desc = self._resolve_subject(subject)
        cause_text = cause or "physics"

        # If the prediction text is already a full, meaningful sentence, use it directly
        # Only wrap in template if it's a short fragment
        if prediction and len(prediction) > 60:
            result = prediction
        else:
            # Determine the right verb based on cause/prediction context
            lower_pred = prediction.lower() if prediction else ""
            lower_cause = cause_text.lower()
            if "fall" in lower_pred or "drop" in lower_pred or "gravity" in lower_cause:
                verb = "fall downward"
            elif "slide" in lower_pred or "friction" in lower_cause:
                verb = "decelerate and stop"
            elif "bounce" in lower_pred or "elastic" in lower_cause:
                verb = "bounce back"
            elif "collide" in lower_pred or "momentum" in lower_cause or "collision" in lower_cause:
                verb = "transfer momentum"
            elif "roll" in lower_pred:
                verb = "roll along the surface"
            else:
                verb = prediction if prediction else "respond according to its physical properties"

            pattern = self.scaffolder.get_pattern("prediction")
            result = self.scaffolder.fill_pattern(pattern, {
                "adj": "",
                "noun": desc,
                "verb": verb,
                "cause": cause_text,
                "verb_phrase": prediction if prediction else verb,
            })

        if details:
            result += "\n\nDetails:\n" + "\n".join(f"  - {d}" for d in details)
        return result

    def generate_explanation(self, concept: str, related_objects: Optional[List[Tuple[str, float]]] = None) -> str:
        """Generate a concept explanation from VSA knowledge."""
        concept_lower = concept.lower()
        defn = self._definitions.get(concept_lower)

        if defn:
            result = f"**{concept}**\n\n"
            result += f"Definition: {defn['definition']}\n\n"
            result += f"Physics: {defn['physics']}\n\n"
            if defn.get("examples"):
                result += "Examples:\n"
                for ex in defn["examples"]:
                    result += f"  - {ex}\n"
        else:
            # Try to generate from VSA decomposition
            result = f"**{concept}**\n\n"
            result += self._generate_from_vsa(concept)

        if related_objects:
            result += "\nRelated objects in my experience:\n"
            for obj_id, score in related_objects[:5]:
                desc = self.generate_description(obj_id)
                result += f"  - {obj_id}: {desc} (similarity: {score:.2f})\n"

        return result

    def generate_counterfactual(self, subject: str, change: str,
                                 reasoning: str, prediction: str) -> str:
        """Generate a counterfactual reasoning response."""
        pattern = self.scaffolder.get_pattern("counterfactual")
        condition = f"the {subject} were {change}"
        return self.scaffolder.fill_pattern(pattern, {
            "condition": condition,
            "prediction": prediction,
        })

    def generate_action_plan(self, action: str, target: str,
                              steps: List[str]) -> str:
        """Generate an action plan response."""
        result = f"I will {action} the {target}.\n\nPlan:\n"
        for i, step in enumerate(steps, 1):
            result += f"  {i}. {step}\n"
        return result

    def generate_code(self, task: str, language: str = "python",
                      context: Optional[Dict[str, Any]] = None) -> str:
        """Generate code from a natural language task description.

        Uses VSA pattern matching to find the best code template,
        then fills in the slots based on the task description.
        """
        # Find matching code patterns
        matches = self._match_code_patterns(task, language)
        if not matches:
            return self._generate_code_fallback(task, language)

        best_pattern, score = matches[0]

        # Extract parameters from task description
        params = self._extract_code_params(task, best_pattern)

        # Fill the template
        code = best_pattern.template
        for key, value in params.items():
            code = code.replace(f"{{{key}}}", str(value))

        # Clean up unfilled slots with reasonable defaults
        code = self._fill_code_defaults(code, best_pattern, params)

        return code

    def generate_from_reasoning(self, parsed_query: dict,
                                 reasoning_result: dict) -> str:
        """Main entry point: generate response from reasoning results.

        This replaces the template-based Responder.respond().
        """
        intent = parsed_query.get("intent", "unknown")
        kind = reasoning_result.get("kind")

        # Route to specific generators based on result kind
        if kind == "abstract_reasoning":
            return self._gen_abstract(reasoning_result)
        if kind == "theory_of_mind":
            return self._gen_social(reasoning_result)
        if kind == "conversation":
            return reasoning_result.get("response", "")
        if kind == "memory":
            return self._gen_memory(reasoning_result)
        if kind == "cross_domain_transfer":
            return self._gen_transfer(reasoning_result)
        if kind == "abstract_task":
            return self._gen_abstract_task(reasoning_result)
        if kind == "code_explanation":
            return self._gen_code_explanation(reasoning_result)
        if kind == "algorithm_comparison":
            return self._gen_algorithm_comparison(reasoning_result)
        if kind == "code_reasoning":
            return self._gen_code_with_reasoning(parsed_query, reasoning_result)

        # Route based on intent
        if intent == "question":
            return self._gen_question(parsed_query, reasoning_result)
        elif intent == "command":
            return self._gen_command(parsed_query, reasoning_result)
        elif intent == "explanation":
            return self._gen_explanation(parsed_query, reasoning_result)
        elif intent == "counterfactual":
            return self._gen_counterfactual(parsed_query, reasoning_result)
        elif intent == "code":
            return self.generate_code(
                parsed_query.get("text", ""),
                context=reasoning_result,
            )
        else:
            return self._gen_unknown(parsed_query)

    # ------------------------------------------------------------------
    # Internal generation helpers
    # ------------------------------------------------------------------

    def _resolve_subject(self, subject: str) -> str:
        """Resolve a subject description to natural language."""
        # Try to find in recipe store
        recipe = self.recipe_store.get_recipe(subject)
        if recipe:
            return self.generate_description(subject)

        # Check if it matches any known word
        entry = self.mapper.find_word(subject)
        if entry:
            return entry.text

        return subject

    def _generate_from_vsa(self, concept: str) -> str:
        """Generate description by decomposing a VSA concept."""
        # Try to decompose as an attribute ID
        cat, name = self.primitives.resolve_id(concept)
        if cat:
            entry = self.mapper.concept_to_word(cat, name)
            if entry:
                return f"{concept} is a {cat} attribute meaning '{entry.text}'."

        return f"I have a concept '{concept}' in my VSA space but need more experience to describe it."

    def _gen_question(self, parsed: dict, result: dict) -> str:
        """Generate a question response."""
        if "prediction" in result:
            details = []
            if result.get("matched_objects"):
                for obj_id, score in result["matched_objects"][:3]:
                    desc = self.generate_description(obj_id)
                    details.append(f"{obj_id}: {desc} (similarity: {score:.2f})")
            if result.get("applicable_rules"):
                details.extend(result["applicable_rules"])

            # Extract subject from parsed query's matching objects (keyword-based)
            subject = "the object"
            if parsed.get("matching_objects"):
                best_obj = parsed["matching_objects"][0][0]
                desc = self.generate_description(best_obj)
                subject = desc
            elif result.get("matched_objects"):
                best_obj = result["matched_objects"][0][0]
                desc = self.generate_description(best_obj)
                subject = desc

            # Extract cause from applicable rules
            cause = "physics"
            if result.get("applicable_rules"):
                cause = result["applicable_rules"][0]

            return self.generate_prediction(
                subject=subject,
                prediction=result["prediction"],
                cause=cause,
                details=details if details else None,
            )

        if "matched_objects" in result:
            matches = result["matched_objects"]
            if matches:
                lines = []
                for obj_id, score in matches:
                    desc = self.generate_description(obj_id)
                    lines.append(f"  - {obj_id}: {desc} (score: {score:.2f})")
                return f"I found {len(matches)} object(s) matching your description:\n" + "\n".join(lines)

        # Check if the result is an explanation (from concept matching)
        if result.get("explanation") and result.get("concept"):
            return self._gen_explanation(parsed, result)

        return f"I couldn't find objects matching '{parsed.get('text', '')}' in my knowledge base. I may need to explore more."

    def _gen_command(self, parsed: dict, result: dict) -> str:
        """Generate a command response."""
        if "plan" in result:
            return self.generate_action_plan(
                action=result.get("action", "execute"),
                target=result.get("target", "object"),
                steps=result["plan"],
            )
        return f"I understand you want to {parsed.get('text', '')}, but I cannot execute this command."

    def _gen_explanation(self, parsed: dict, result: dict) -> str:
        """Generate an explanation response."""
        concept = result.get("concept", parsed.get("text", ""))

        # Check if this is a code explanation from reasoning engine
        if result.get("kind") == "code_explanation":
            return self._gen_code_explanation(result)

        # Use explanation data from the result if available (e.g., from learned concepts)
        explanation = result.get("explanation", {})
        if explanation.get("definition"):
            response = f"**{concept}**\n\n"
            response += f"Definition: {explanation['definition']}\n\n"
            if explanation.get("physics"):
                response += f"Physics: {explanation['physics']}\n\n"
            if explanation.get("examples"):
                response += "Examples:\n"
                for ex in explanation["examples"]:
                    response += f"  - {ex}\n"
            return response

        related = result.get("related_objects")
        return self.generate_explanation(concept, related)

    def _gen_code_explanation(self, result: dict) -> str:
        """Generate explanation for code/algorithm concepts."""
        concept = result.get("concept", "unknown")
        explanation = result.get("explanation", {})

        response = f"**{concept}**\n\n"
        response += f"Definition: {explanation.get('definition', '')}\n\n"

        if explanation.get("algorithm"):
            response += f"Algorithm: {explanation['algorithm']}\n\n"

        complexity = explanation.get("complexity", {})
        if complexity:
            response += "Complexity:\n"
            for k, v in complexity.items():
                response += f"  - {k}: {v}\n"
            response += "\n"

        use_cases = explanation.get("use_cases", [])
        if use_cases:
            response += "Use cases:\n"
            for uc in use_cases:
                response += f"  - {uc}\n"

        return response

    def _gen_algorithm_comparison(self, result: dict) -> str:
        """Generate a comparison between two algorithms."""
        algorithms = result.get("algorithms", [])
        if len(algorithms) < 2:
            return "I need two algorithms to compare."

        algo1, algo2 = algorithms[0], algorithms[1]
        response = f"Comparing **{algo1}** vs **{algo2}**:\n\n"

        # Show each algorithm's properties
        for algo in [algo1, algo2]:
            algo_info = result.get(algo, {})
            response += f"**{algo}:**\n"
            if algo_info.get("definition"):
                response += f"  {algo_info['definition']}\n"
            complexity = algo_info.get("complexity", {})
            if complexity:
                complexity_str = ", ".join(f"{k}: {v}" for k, v in complexity.items())
                response += f"  Complexity: {complexity_str}\n"
            response += "\n"

        # Show comparison points
        comparison_points = result.get("comparison_points", [])
        if comparison_points:
            response += "Key differences:\n"
            for point in comparison_points:
                aspect = point.get("aspect", "")
                response += f"  - {aspect}:\n"
                response += f"    {algo1}: {point.get(algo1, 'N/A')}\n"
                response += f"    {algo2}: {point.get(algo2, 'N/A')}\n"

        # Show shared concepts
        shared = result.get("shared_concepts", [])
        if shared:
            response += f"\nShared concepts: {', '.join(shared)}"

        return response

    def _gen_code_with_reasoning(self, parsed: dict, result: dict) -> str:
        """Generate code with reasoning context from VSA."""
        task = result.get("task", parsed.get("text", ""))
        reasoning = result.get("reasoning", {})

        # Generate the code
        code = self.generate_code(task, context=result)

        # Add reasoning context
        response = ""
        suggestions = reasoning.get("suggestions", [])
        if suggestions:
            response += "Based on my analysis:\n"
            for s in suggestions[:3]:
                response += f"  - {s.get('algorithm', '')}: {s.get('reason', '')}\n"
            response += "\n"

        response += code
        return response

    def _gen_counterfactual(self, parsed: dict, result: dict) -> str:
        """Return the reasoning directly — the causal engine already built the text."""
        return result.get("reasoning") or result.get("prediction", "")

    def _gen_abstract(self, result: dict) -> str:
        """Generate an abstract reasoning response."""
        roots = ", ".join(result.get("root_concepts", [])) or "unknown"
        chains = result.get("chains", [])
        applications = result.get("applications", [])

        response = f"Abstract reasoning activated: {roots}\n\n"

        if chains:
            response += "Reasoning chain:\n"
            for chain in chains[:6]:
                response += f"  - {' -> '.join(chain)}\n"

        if applications:
            response += "\nConcrete implications:\n"
            for app in applications[:6]:
                response += f"  - {app}\n"

        return response

    def _gen_social(self, result: dict) -> str:
        """Generate a theory-of-mind response."""
        agent = result.get("agent", "unknown agent")
        answer = result.get("answer", "")
        if answer:
            return f"Model for {agent}: {answer}"
        return f"No mental-state details known for {agent}."

    def _gen_memory(self, result: dict) -> str:
        """Generate a memory response."""
        action = result.get("action")
        records = result.get("records", [])

        if action == "stored" and records:
            return f"I stored that in long-term memory: {records[0].get('content', '')}"

        if records:
            lines = [f"  - [{r.get('memory_type', 'memory')}] {r.get('content', '')}"
                     for r in records[:5]]
            return "Relevant long-term memories:\n" + "\n".join(lines)

        return "No matching memory found yet."

    def _gen_transfer(self, result: dict) -> str:
        """Generate a cross-domain transfer response."""
        hypotheses = result.get("hypotheses", [])
        if hypotheses:
            lines = []
            for h in hypotheses[:5]:
                targets = ", ".join(h.get("target_hypotheses", []))
                lines.append(f"  - {h['schema']}: {h['abstraction']} -> {targets}")
            source = result.get("source_domain", "source")
            target = result.get("target_domain", "target")
            return f"Cross-domain transfer from {source} to {target}:\n" + "\n".join(lines)
        return "No reusable schema matched yet; more source-domain experience is needed."

    def _gen_abstract_task(self, result: dict) -> str:
        """Generate an abstract task response."""
        domain = result.get("domain", "abstract").title()
        premises = "\n".join(f"  - {p}" for p in result.get("premises", []))
        rules = "\n".join(f"  - {r}" for r in result.get("rules", []))
        conclusion = result.get("conclusion", "")

        response = f"{domain} reasoning\n\n"
        if premises:
            response += f"Premises:\n{premises}\n\n"
        if rules:
            response += f"Rules:\n{rules}\n\n"
        response += f"Conclusion: {conclusion}"
        return response

    def _gen_unknown(self, parsed: dict) -> str:
        """Generate a response for unknown intent."""
        query = parsed.get("text", "")
        return (f"I'm not sure I understand '{query}'. Could you rephrase? "
                "I can answer questions about objects, explain physics concepts, "
                "generate code, or execute physical commands.")

    # ------------------------------------------------------------------
    # Code generation helpers
    # ------------------------------------------------------------------

    def _match_code_patterns(self, task: str, language: str
                              ) -> List[Tuple[CodePattern, float]]:
        """Match a task description to code patterns."""
        task_lower = task.lower()
        matches = []

        for pattern in self._code_patterns.values():
            if pattern.language != language:
                continue

            # Score based on keyword overlap, with bonus for multi-word matches
            score = 0.0
            matched_keywords = 0
            matched_kw_list = []
            for kw in pattern.keywords:
                if kw in task_lower:
                    # Multi-word keywords get higher weight
                    weight = len(kw.split())
                    score += weight
                    matched_keywords += 1
                    matched_kw_list.append(kw)

            if matched_keywords > 0:
                # Normalize by number of keywords, but reward more matches
                score = score / len(pattern.keywords) * (1 + matched_keywords * 0.2)

                # Bonus for matching the primary action (sort > list, search > array)
                primary_actions = ["sort", "search", "traverse", "push", "pop",
                                   "enqueue", "dequeue", "bfs", "dfs"]
                for action in primary_actions:
                    if action in matched_kw_list:
                        score *= 1.5
                        break

                matches.append((pattern, score))

        matches.sort(key=lambda x: x[1], reverse=True)
        return matches

    def _extract_code_params(self, task: str, pattern: CodePattern
                              ) -> Dict[str, str]:
        """Extract parameters from task description for code template."""
        params: Dict[str, str] = {}
        task_lower = task.lower()

        # Extract function/class name
        name_found = False
        name_match = re.search(
            r'(?:called|named)\s+(\w+)', task, re.IGNORECASE)
        if name_match:
            params["name"] = name_match.group(1)
            name_found = True

        if not name_found:
            # Try to find a meaningful name from the task
            # Look for patterns like "binary search function", "linked list class"
            name_patterns = [
                r'(binary\s+search)',
                r'(linked\s+list)',
                r'(graph\s+(?:bfs|dfs|traversal))',
                r'(quicksort|mergesort|heap\s*sort)',
            ]
            for pat in name_patterns:
                m = re.search(pat, task, re.IGNORECASE)
                if m:
                    params["name"] = m.group(1).replace(" ", "_").lower()
                    name_found = True
                    break

        if not name_found:
            # Fallback: extract last meaningful word before "function"/"class"
            name_match = re.search(
                r'(?:function|def|class|implement|write)\s+(?:a\s+)?(?:\w+\s+)*?(\w+)',
                task, re.IGNORECASE)
            if name_match:
                candidate = name_match.group(1).lower()
                # Filter out common words
                if candidate not in {"a", "an", "the", "that", "for", "to", "with",
                                      "function", "class", "code", "program", "write",
                                      "implement", "create", "make"}:
                    params["name"] = candidate
                    name_found = True

        if not name_found and "name" in pattern.template:
            # Generate a name from the task
            words = re.findall(r'[a-z]+', task_lower)
            # Filter out common stop words
            stop_words = {"a", "an", "the", "to", "for", "in", "of", "and", "or", "is",
                          "that", "this", "with", "from", "it", "write", "create", "make",
                          "define", "implement", "build"}
            meaningful = [w for w in words if w not in stop_words][:3]
            params["name"] = "_".join(meaningful) if meaningful else "my_function"

        # Extract parameters
        param_match = re.search(
            r'(?:parameters?|arguments?|params?|takes?|accepts?)\s+(.+?)(?:\.|$)',
            task, re.IGNORECASE)
        if param_match:
            params["params"] = param_match.group(1).strip()
        elif "params" in pattern.template:
            params["params"] = ""

        # Extract description/docstring
        params["docstring"] = task[:100]
        params["description"] = task

        # Extract language
        params["language"] = pattern.language

        return params

    def _fill_code_defaults(self, code: str, pattern: CodePattern,
                            params: Dict[str, str]) -> str:
        """Fill remaining slots with reasonable defaults."""
        defaults = {
            "body": "pass",
            "init_body": "pass",
            "methods": "",
            "return_value": "None",
            "then_body": "pass",
            "else_body": "pass",
            "try_body": "pass",
            "except_body": "pass",
            "exception": "Exception",
            "item": "item",
            "iterable": "items",
            "condition": "True",
            "expr": "item",
            "list_name": "data",
            "key_expr": "x",
            "reverse": "False",
            "path": "data.txt",
            "var": "content",
            "content": "data",
            "method": "get",
            "url": "https://api.example.com",
            "extra": "",
            "step1_desc": "clean",
            "step1": "[x.strip() for x in data]",
            "step2_desc": "filter",
            "step2": "[x for x in data if x]",
            "step3_desc": "transform",
            "step3": "data",
            "pre_logic": "# before",
            "post_logic": "# after",
            "base_case_0": "0",
            "base_case_1": "1",
            "recurrence": "memo[i-1] + memo[i-2]",
        }

        for key, value in defaults.items():
            placeholder = f"{{{key}}}"
            if placeholder in code and key not in params:
                code = code.replace(placeholder, value)

        return code

    def _generate_code_fallback(self, task: str, language: str) -> str:
        """Fallback code generation when no pattern matches."""
        return (f"# Task: {task}\n"
                f"# Language: {language}\n"
                f"# No matching code pattern found.\n"
                f"# Try rephrasing with keywords like: function, class, loop, sort, etc.")

    def register_code_pattern(self, pattern: CodePattern):
        """Register a new code pattern."""
        self._code_patterns[pattern.name] = pattern

    # ------------------------------------------------------------------
    # Code explanation (code -> natural language)
    # ------------------------------------------------------------------

    def explain_code(self, code: str) -> str:
        """Generate a natural language explanation of code.

        This is the reverse of code generation: given code, explain what it does.
        Uses pattern matching and VSA concepts to generate explanations.
        """
        code_stripped = code.strip()

        # Detect what kind of code this is
        detected = self._detect_code_type(code_stripped)

        if not detected:
            return "I can see this is code, but I need more context to explain it."

        code_type, details = detected

        # Generate explanation based on type
        if code_type == "function":
            return self._explain_function(code_stripped, details)
        elif code_type == "class":
            return self._explain_class(code_stripped, details)
        elif code_type == "algorithm":
            return self._explain_algorithm(code_stripped, details)
        else:
            return f"This code appears to implement {code_type}."

    def _detect_code_type(self, code: str) -> Optional[Tuple[str, dict]]:
        """Detect the type of code and extract details."""
        details = {}

        # Function detection
        func_match = re.search(r'def\s+(\w+)\s*\(([^)]*)\)', code)
        if func_match:
            details["name"] = func_match.group(1)
            details["params"] = func_match.group(2)
            # Check if it's a known algorithm
            name_lower = details["name"].lower()
            for pattern_name, pattern in self._code_patterns.items():
                if any(kw in name_lower for kw in pattern.keywords):
                    return ("algorithm", {"pattern": pattern, **details})
            return ("function", details)

        # Class detection
        class_match = re.search(r'class\s+(\w+)', code)
        if class_match:
            details["name"] = class_match.group(1)
            # Check for methods
            methods = re.findall(r'def\s+(\w+)\s*\(', code)
            details["methods"] = methods
            return ("class", details)

        return None

    def _explain_function(self, code: str, details: dict) -> str:
        """Explain a function."""
        name = details.get("name", "this function")
        params = details.get("params", "")

        explanation = f"This code defines a function called **{name}**"

        if params:
            explanation += f" that takes parameters: {params}"
        explanation += ".\n\n"

        # Try to infer purpose from the code structure
        if "return" in code:
            explanation += "It computes and returns a result."

        return explanation

    def _explain_class(self, code: str, details: dict) -> str:
        """Explain a class."""
        name = details.get("name", "this class")
        methods = details.get("methods", [])

        explanation = f"This code defines a class called **{name}**"

        if methods:
            method_list = ", ".join(methods[:5])
            explanation += f" with methods: {method_list}"
        explanation += ".\n\n"

        # Try to infer the data structure
        if "push" in methods and "pop" in methods:
            explanation += "This appears to be a stack (LIFO) data structure."
        elif "enqueue" in methods and "dequeue" in methods:
            explanation += "This appears to be a queue (FIFO) data structure."
        elif "insert" in methods and "search" in methods:
            explanation += "This appears to be a data structure for storing and retrieving elements."
        elif "get" in methods and "put" in methods:
            explanation += "This appears to be a key-value store or cache."

        return explanation

    def _explain_algorithm(self, code: str, details: dict) -> str:
        """Explain an algorithm."""
        pattern = details.get("pattern")
        name = details.get("name", "an algorithm")

        if pattern:
            explanation = f"This code implements **{pattern.description}**"
            if pattern.name in ["quicksort", "merge_sort", "heap_sort"]:
                explanation += ", a sorting algorithm"
            elif pattern.name in ["binary_search"]:
                explanation += ", a search algorithm"
            elif pattern.name in ["bfs", "dfs", "dijkstra"]:
                explanation += ", a graph traversal algorithm"
            explanation += ".\n\n"

            # Add complexity info from VSA reasoning
            algo_name = pattern.name.replace("_", " ")
            code_exp = self._definitions.get(algo_name.lower())
            if code_exp:
                explanation += f"Purpose: {code_exp.get('definition', '')}"
        else:
            explanation = f"This code implements **{name}**"

        return explanation
